### ISSUE TITLE
Uncaught SoapFault exception: [Client] looks like we got no XML document

### ISSUE THREAD

**Issue by fedejuret** [Ingenico-NPS-Latam/nps-sdk-php#5]
Hi, I have this error when try to call `payOnline3p`.

This is the full error:
```
Uncaught SoapFault exception: [Client] looks like we got no XML document in /home/customer/www/911hoteles.com.ar/public_html/vendor/nps/php-sdk/src/NpsSDK/Sdk.php:40
Stack trace:
#0 /home/customer/www/911hoteles.com.ar/public_html/vendor/nps/php-sdk/src/NpsSDK/Sdk.php(40): SoapClient->__soapCall('PayOnLine_3p', Array)
#1 /home/customer/www/911hoteles.com.ar/public_html/vendor/nps/php-sdk/src/NpsSDK/Sdk.php(110): NpsSDK\Sdk->callClient('PayOnLine_3p', Array)
#2 /home/customer/www/911hoteles.com.ar/public_html/d/checkout_nps.php(80): NpsSDK\Sdk->payOnline3p(Array)
#3 {main}
  thrown in /home/customer/www/911hoteles.com.ar/public_html/vendor/nps/php-sdk/src/NpsSDK/Sdk.php
on line 40
```

And this is the array that I'm using to call the method:

```php
[
  "psp_Version" => "2.2",
  "psp_MerchantId" => "******",
  "psp_TxSource" => "WEB",
  "psp_PosDateTime" => "2022-08-03 11:26:39",
  "psp_Country" => "ARG",
  "psp_FrmLanguage" => "ES",
  "psp_CustomerMail" => "customeremail@email.com",
  "psp_MerchantMail" => "merchantemail@email.com",
  "psp_FrmBackButtonURL" => "returnurl.com.ar",
  "psp_ReturnURL" => "returnurl.com.ar",
  "psp_MerchOrderId" => "104401",
  "psp_MerchTxRef" => "104401-2457",
  "psp_PurchaseDescription" => "Some text here",
  "psp_NumPayments" => "1",
  "psp_Currency" => "032",
  "psp_Amount" => 700000.0,
  "psp_Product" => "14"
]
```

Some days ago (two days ago), the SDK works fine. And we don't make any change on the code.
Thank you!

**Comment by IngenicoNPSLatam** [comment]
We can't reproduce the error. Reopen the issue if you still have problems.

You have an error in the psp_Amount field. It should be an integer, without decimal points. Even then, we can't reproduce the error you received.
